version: '3.8'
services:
  app:
    build: 
      dockerfile: Dockerfile
    volumes:
      - data:/opt/app
    ports:     
     - "5000:5000"
    # command: "python3 manage.py initdb"


volumes:
  data: